In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import mean_squared_error
import xgboost as xgb
from xgboost import plot_importance
from sklearn.preprocessing import PolynomialFeatures
%matplotlib inline

C:\Users\li\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
input_train=pd.read_csv("train.csv",encoding="gb2312")
input_test=pd.read_csv("test.csv",encoding="gb2312")
example=pd.read_csv("submit_example.csv",encoding="gb2312")

In [3]:
df1_train=input_train.iloc[1:,[x for x in range(23)]+[23]]
df2_train=input_train.iloc[1:,[x for x in range(23)]+[24]]
df3_train=input_train.iloc[1:,[x for x in range(23)]+[25]]
df4_train=input_train.iloc[1:,[x for x in range(23)]+[26]]

In [4]:
poly = PolynomialFeatures(degree=3)
np_train = poly.fit_transform(df1_train.iloc[:,[1,2,3,4,5,8]])
df_new_features=pd.DataFrame(np_train)
df_new_features.head()

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,1.0,586.40002,187.129,1859.5271,660.37347,2997.8721,576.60004,343864.983456,109732.449343,1.090427e+06,...,2.879843e+08,1.307351e+09,2.514513e+08,5.934933e+09,1.141504e+09,2.195528e+08,2.694259e+10,5.182041e+09,9.966954e+08,1.917008e+08
1,1.0,586.40002,187.129,1859.0161,662.54938,2997.8721,576.60004,343864.983456,109732.449343,1.090127e+06,...,2.908404e+08,1.315981e+09,2.531111e+08,5.954488e+09,1.145265e+09,2.202762e+08,2.694259e+10,5.182041e+09,9.966954e+08,1.917008e+08
2,1.0,586.40002,187.129,1859.0161,662.54938,2997.8721,576.60004,343864.983456,109732.449343,1.090127e+06,...,2.908404e+08,1.315981e+09,2.531111e+08,5.954488e+09,1.145265e+09,2.202762e+08,2.694259e+10,5.182041e+09,9.966954e+08,1.917008e+08
3,1.0,586.40002,187.129,1858.8391,662.36023,2998.6790,576.60004,343864.983456,109732.449343,1.090023e+06,...,2.905914e+08,1.315584e+09,2.529666e+08,5.955993e+09,1.145246e+09,2.202133e+08,2.696435e+10,5.184831e+09,9.969636e+08,1.917008e+08
4,1.0,586.40002,187.129,1858.8391,662.36023,2998.6790,576.60004,343864.983456,109732.449343,1.090023e+06,...,2.905914e+08,1.315584e+09,2.529666e+08,5.955993e+09,1.145246e+09,2.202133e+08,2.696435e+10,5.184831e+09,9.969636e+08,1.917008e+08

In [5]:
# model1有用的组合特征：14,50,19,9,8,68,10,26,11,55,35,12,30,81,29,54,65,40,15,46,82,31,47,25,63,32,33,73,21,71
# test_1= xgb.XGBRegressor(n_estimators=1100,n_jobs=-1,max_depth=5,colsample_bytree=0.8,subsample=0.9)
# test_1.fit(df_new_features.values,df1_train.iloc[:,-1].values)
# fig1,ax1 = plt.subplots(figsize=(15,15))
# plot_importance(test_1,height=0.5,ax=ax1)
# plt.show()

In [6]:
# test_2= xgb.XGBRegressor(n_estimators=1100,n_jobs=-1,max_depth=5,colsample_bytree=0.8,subsample=0.9)
# test_2.fit(df_new_features.values,df2_train.iloc[:,-1].values)
# fig2,ax2 = plt.subplots(figsize=(15,15))
# plot_importance(test_2,height=0.5,ax=ax2)
# plt.show()

In [7]:
df_train = pd.concat([pd.DataFrame(df1_train.iloc[:,:23].values),df_new_features.iloc[:,7:]],axis=1)
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,14001,586.40002,187.129,1859.5271,660.37347,2997.8721,348.90002,38.088829,576.60004,261,...,2.879843e+08,1.307351e+09,2.514513e+08,5.934933e+09,1.141504e+09,2.195528e+08,2.694259e+10,5.182041e+09,9.966954e+08,1.917008e+08
1,14002,586.40002,187.129,1859.0161,662.54938,2997.8721,348.90002,38.088829,576.60004,261,...,2.908404e+08,1.315981e+09,2.531111e+08,5.954488e+09,1.145265e+09,2.202762e+08,2.694259e+10,5.182041e+09,9.966954e+08,1.917008e+08
2,14003,586.40002,187.129,1859.0161,662.54938,2997.8721,348.90002,38.088829,576.60004,261,...,2.908404e+08,1.315981e+09,2.531111e+08,5.954488e+09,1.145265e+09,2.202762e+08,2.694259e+10,5.182041e+09,9.966954e+08,1.917008e+08
3,14004,586.40002,187.129,1858.8391,662.36023,2998.679,348.90002,38.088829,576.60004,261,...,2.905914e+08,1.315584e+09,2.529666e+08,5.955993e+09,1.145246e+09,2.202133e+08,2.696435e+10,5.184831e+09,9.969636e+08,1.917008e+08
4,14005,586.40002,187.129,1858.8391,662.36023,2998.679,348.90002,38.088829,576.60004,261,...,2.905914e+08,1.315584e+09,2.529666e+08,5.955993e+09,1.145246e+09,2.202133e+08,2.696435e+10,5.184831e+09,9.969636e+08,1.917008e+08

In [8]:
df_test_value=input_test.iloc[1:,:]
np_test = poly.fit_transform(df_test_value.iloc[:,[1,2,3,4,5,8]])
df_test = pd.concat([pd.DataFrame(df_test_value.iloc[:,:].values),pd.DataFrame(np_test).iloc[:,7:]],axis=1)
df_test.head()

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,1,600,203.52461,2264.4098,760.75397,2998.3782,363.5,43.312592,590.60004,293.90002,...,4.402838e+08,1.735301e+09,3.418078e+08,6.839385e+09,1.347175e+09,2.653574e+08,2.695624e+10,5.309655e+09,1.045860e+09,2.060063e+08
1,2,600,203.52461,2264.4098,760.75397,2998.3782,363.5,43.312592,590.5,293.90002,...,4.402838e+08,1.735301e+09,3.417499e+08,6.839385e+09,1.346947e+09,2.652675e+08,2.695624e+10,5.308756e+09,1.045505e+09,2.059016e+08
2,3,600,203.4463,2268.2728,760.75397,2998.3782,363.5,43.312592,590.5,293.90002,...,4.402838e+08,1.735301e+09,3.417499e+08,6.839385e+09,1.346947e+09,2.652675e+08,2.695624e+10,5.308756e+09,1.045505e+09,2.059016e+08
3,4,600,203.4463,2268.2728,760.75397,2998.3782,363.5,43.312592,590.5,293.90002,...,4.402838e+08,1.735301e+09,3.417499e+08,6.839385e+09,1.346947e+09,2.652675e+08,2.695624e+10,5.308756e+09,1.045505e+09,2.059016e+08
4,5,600,203.3847,2274.1449,759.99713,2998.3782,363.5,43.312592,590.5,293.90002,...,4.389710e+08,1.731850e+09,3.410702e+08,6.832581e+09,1.345607e+09,2.650036e+08,2.695624e+10,5.308756e+09,1.045505e+09,2.059016e+08

In [9]:
# model1 = xgb.XGBRegressor(n_estimators=1100,n_jobs=-1,max_depth=5,colsample_bytree=0.2,subsample=0.7)
# model2 = xgb.XGBRegressor(n_estimators=1100,n_jobs=-1,max_depth=5,colsample_bytree=0.2,subsample=0.7)
# model3 = xgb.XGBRegressor(n_estimators=1100,n_jobs=-1,max_depth=5,colsample_bytree=0.2,subsample=0.7)
# model4 = xgb.XGBRegressor(n_estimators=1100,n_jobs=-1,max_depth=5,colsample_bytree=0.2,subsample=0.7)
model1 = xgb.XGBRegressor(learning_rate=0.05,n_estimators=1100,n_jobs=-1,max_depth=3,colsample_bytree=0.2,subsample=0.7,min_child_weight=2)
model2 = xgb.XGBRegressor(learning_rate=0.31,n_estimators=1100,n_jobs=-1,max_depth=7,colsample_bytree=0.2,subsample=1,min_child_weight=2.5)
model3 = xgb.XGBRegressor(learning_rate=0.15,n_estimators=1100,n_jobs=-1,max_depth=2,colsample_bytree=0.1,subsample=0.6,min_child_weight=1.5)
model4 = xgb.XGBRegressor(learning_rate=0.1,n_estimators=1100,n_jobs=-1,max_depth=7,colsample_bytree=0.2,subsample=0.7,min_child_weight=1)

In [10]:
model1.fit(df_train.iloc[:,1:].values,df1_train.iloc[:,-1].values)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.2, gamma=0, learning_rate=0.05, max_delta_step=0,
       max_depth=3, min_child_weight=2, missing=None, n_estimators=1100,
       n_jobs=-1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.7)

In [11]:
model2.fit(df_train.iloc[:,1:].values,df2_train.iloc[:,-1].values)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.2, gamma=0, learning_rate=0.31, max_delta_step=0,
       max_depth=7, min_child_weight=2.5, missing=None, n_estimators=1100,
       n_jobs=-1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [12]:
model3.fit(df_train.iloc[:,1:].values,df3_train.iloc[:,-1].values)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.1, gamma=0, learning_rate=0.15, max_delta_step=0,
       max_depth=2, min_child_weight=1.5, missing=None, n_estimators=1100,
       n_jobs=-1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.6)

In [13]:
model4.fit(df_train.iloc[:,1:].values,df4_train.iloc[:,-1].values)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.2, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=7, min_child_weight=1, missing=None, n_estimators=1100,
       n_jobs=-1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.7)

In [14]:
predict1=model1.predict(df_test.iloc[:,1:].values)
predict2=model2.predict(df_test.iloc[:,1:].values)
predict3=model3.predict(df_test.iloc[:,1:].values)
predict4=model4.predict(df_test.iloc[:,1:].values)

In [15]:
pd1=pd.concat([pd.DataFrame(df_test.iloc[:,0].values,columns=['id']),pd.DataFrame(['A' for i in range(14000)],columns=['Seq_tag']),pd.DataFrame(predict1,columns=['Predict'])],axis=1)
pd2=pd.concat([pd.DataFrame(df_test.iloc[:,0].values,columns=['id']),pd.DataFrame(['B' for i in range(14000)],columns=['Seq_tag']),pd.DataFrame(predict2,columns=['Predict'])],axis=1)
pd3=pd.concat([pd.DataFrame(df_test.iloc[:,0].values,columns=['id']),pd.DataFrame(['C' for i in range(14000)],columns=['Seq_tag']),pd.DataFrame(predict3,columns=['Predict'])],axis=1)
pd4=pd.concat([pd.DataFrame(df_test.iloc[:,0].values,columns=['id']),pd.DataFrame(['D' for i in range(14000)],columns=['Seq_tag']),pd.DataFrame(predict4,columns=['Predict'])],axis=1)

In [16]:
pd_out=pd.concat([pd1,pd2,pd3,pd4])

In [17]:
pd_out.to_csv('result7.csv',index=False)